### PR TITLE
Improved to be strict

### PR DESCRIPTION
**Pull request by worthmine**
I fixed the inconvenience I find with using this module.

The PR #1 I sent before was very terrible. I apologize for the matter.

But I am confident about this one.

### CODE REVIEW

**Comment by miyagawa** [comment]
> I fixed the inconvenience I find with using this module.

What inconvenience? You have to explain what problem this is trying to solve.

Just by looking at it, you're trying to determine if the era is a valid one for a given date. That is already possible by round-tripping the era to a Gregorian year, and then back to the era, such as:

```
use strict;
use utf8;
use Date::Japanese::Era;

sub is_valid_era {
    my( $name, $year, $month, $day ) = @_;

    my $ok = eval {
        my $era1 = Date::Japanese::Era->new( $name, $year );
        my $era2 = Date::Japanese::Era->new( $era1->gregorian_year, $month, $day );

        return $era1->name eq $era2->name;
    };

    return $ok if $ok;
    return;
}

warn is_valid_era("平成", 31, 4, 30) ? "OK" : "NOT OK"; 
warn is_valid_era("平成", 31, 5, 1) ? "OK" : "NOT OK"; 
warn is_valid_era("平成", 32, 5, 1) ? "OK" : "NOT OK"; 
```

I generally avoid adding stuff to a module that is already possible outside using it, since adding unnecessary code increases the potential for bugs and increases the maintenance cost.

**Comment by worthmine** [comment]
Thank you for reviewing and replying.

Recently, I'm writing a system for like a medical institution.
And they want to treat the birthdays of their members with Japanese Era, not the Christian era. 
I need to write the system that validates them one by one when they type.

If they were given official document published in 平成( like a driver license),
it may have the expiration date with old described  Era and years like "平成33年mm月dd日まで有効"(it's NOT wrong but invalid with this module).
I thought it would be inconvenient to import these.

I wanted to fix it (if automation was possible) and I thought that allowing to exceed( if possible) was convenient.

**Comment by worthmine** [comment]
Do you accept like [this](https://github.com/worthmine/Date-Japanese-Era/tree/travis)?

**Comment by miyagawa** [comment]
Thank you for the context. 

I guess my snippet above would make it more relaxed, but making it relaxed would require a change. However, I do not like adding such a niche, and changing the behavior based on the number of arguments to new(), which already does for Japanese era/Greagorian input would be fairly complicated.

For this one, I suggest you to simply use an offset based conversion and do not rely on this module. by simply adding 1988 i.e. 平成 33 = 1988 + 33 = 2021.

**Comment by worthmine** [comment]
Thank you for replying.

I don't think the validations for Japanese Era are a niche.

I need to make my system that replaces the Era automatically rather than throwing some errors because the staffs is not necessarily familiar with the computers.
In the system, the birthday entered by the staffs with using Japanese Era will be converted to the date type of mysql to save, and when browsing, it is restored to with the Japanese Era again.
It's the problem that **they can't recognize their typo** until this moment.

Or should I write the yet another which has rich context?

**Comment by miyagawa** [comment]
> In the system, the birthday entered by the staffs with using Japanese Era will be converted to the date type of mysql to save, and when browsing, it is restored to with the Japanese Era again.

Yes, so i suggest using the offset based conversion to convert from Heisei/Reiwa/Showa etc to Gregorian date, then use this module to present to whatever right Japanese Era is, which the module already does.

> I need to make my system that replaces the Era automatically rather than throwing some errors because the staffs is not necessarily familiar with the computers.
...
> It's the problem that they can't recognize their typo until this moment.

To me you're saying two different things here, one is that it should automatically correct the mistakes by accepting invalid combinations (such as Heisei 33) and the other is that you want to invalidate the input. 

Again I think this can easily be done without using this module by simply converting the input based on the offset year.

> Or should I write the yet another which has rich context?

I don't understand why you need those features in this module since in the history of 20 years of this module nobody has asked for this. I'm not saying this is an invalid request, but you can just solve the problem outside this module, or by simply writing a new module forked from this. This module, like all of my software, has a permissive license that allows you to do that.

Adding more code that i don't think we need, is to increase the complexity of the code, likelihood of a new bug, and introduces the maintenance burden.

**Comment by miyagawa** [comment]
```perl
use strict;
use utf8;
use Date::Japanese::Era;

binmode STDOUT, ":utf8";

my %offset = (
    "昭和" => 1925,
    "平成" => 1988,
    "令和" => 2018,
);

sub auto_correct_era {
    my( $name, $year, $month, $day ) = @_;

    printf "%s%d年%d月%d日\n", $name, $year, $month, $day;

    my $gregorian_year = $offset{$name} + $year;
    my $era = Date::Japanese::Era->new( $gregorian_year, $month, $day );

    printf "-> %s%d年\n", $era->name, $era->year;
}

auto_correct_era("昭和", 62, 4, 30);
auto_correct_era("昭和", 64, 4, 30);
auto_correct_era("平成", 31, 4, 30);
auto_correct_era("平成", 31, 5, 1);
auto_correct_era("平成", 32, 4, 30);
auto_correct_era("令和", 1, 4, 30);
auto_correct_era("令和", 2, 5, 1);
```

```
昭和62年4月30日
-> 昭和62年
昭和64年4月30日
-> 平成1年
平成31年4月30日
-> 平成31年
平成31年5月1日
-> 令和1年
平成32年4月30日
-> 令和2年
令和1年4月30日
-> 平成31年
令和2年5月1日
-> 令和2年
```

I believe this code does pretty much what you need.

**Comment by worthmine** [comment]
> I don't understand why you need those features in this module since in the history of 20 years of this module nobody has asked for this. 

I think It's because the Era has not been changed until last year. 

> To me you're saying two different things here,

I think the best UI is to automatically fix and warn before converting to mysql date type.
So they are the same, not two different things.

I give up to convince you  about auto-fix, but I think the validations are still needed. 

I made a code in [another branch](https://github.com/worthmine/Date-Japanese-Era/tree/travis2) which is just added a new constructor like below:

```perl
sub is_valid {    # yet another constructor with validation
    my $class = shift;
    my ( $name, $year, $month, $day ) = @_;
    my $self = eval {
        my $era1 = Date::Japanese::Era->new( $name, $year );
        my $era2 = Date::Japanese::Era->new( $era1->gregorian_year, $month, $day );

        return $era2 if $era1->name eq $era2->name;
    };

    return $self || undef;
}
```

This allows us to implement what I wanted without changing existing code. 
And most of this is what you wrote.

How about this?

**Comment by miyagawa** [comment]
> I think the best UI is to automatically fix and warn before converting to mysql date type.

In that case, I believe that the snippet I pasted above would do that.

By the way it's debatable if that's the best UI - it depends on the use case. This is precisely why putting these decisions into a module is to me a bad idea. The module should only provide building blocks for these, and the user of the module should decide what to do.

> This allows us to implement what I wanted without changing existing code.

Why don't you just place that code in your library files and use it, since you need to call the new class method anyway? 

I understand your eagerness to contribute, but to me it's best to put that logic outside the module, in your control, so that we don't need to add all sorts of different options and behaviors by trying to be a generic solution for everybody.

> And most of this is what you wrote.

By the way this `is_valid` constructor actually doesn't work for inputs like 平成32 because it's invalid, like you pointed out earlier. My offset-based solution would work better for that.

**Comment by worthmine** [comment]
Now I see well your philosophy for maintaining the modules.
You mean that NOT everything that I find convenient will be added as common functions for everybody, Don't you?
And I agree with you.

 I've just wanted to contribute to Japanese Perl community.

I think that those snippets you wrote here must be included into the document.
They are very useful for novice like me.

**Comment by miyagawa** [comment]
> I think that those snippets you wrote here must be included into the document.

Yeah, I think that's a good idea. Let me make a quick update to the doc on how to do that.

**Comment by miyagawa** [comment]
added in 196dba6

**Pull request closed without merging**
